name: CI PR Checker

on: pull_request

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Lua
        uses: leafo/gh-actions-lua@v10

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install LDoc
        run: luarocks install ldoc 1.4.4-1

      - name: Generate Documents
        working-directory: docs
        run: ldoc -i .